import type { Activity, Course, CourseData, CoursePart, Resource } from "../types";

export const CS501_COURSE: Course = {
  university: "Kerala University of Digital Sciences, Innovation and Technology",
  department: "School of Digital Sciences",
  code: "CS501",
  title: "AI Ethics & Governance",
  semester: "Semester 1",
  ltp: "3–0–0",
  credits: 3,
  totalHours: 120,
  type: "elective",
};

export const CS501_PARTS: CoursePart[] = [
  {
    id: "I",
    label: "Unit 1 — Quantifying Bias",
    statLabel: "Bias audit hrs",
    color: "indigo",
  },
  {
    id: "II",
    label: "Unit 2 — Explainable AI",
    statLabel: "XAI & interpretability hrs",
    color: "sky",
  },
  {
    id: "III",
    label: "Unit 3 — Security & Adversarial AI",
    statLabel: "Red team hrs",
    color: "violet",
  },
  {
    id: "IV",
    label: "Unit 4 — Compliance & Governance",
    statLabel: "Compliance hrs",
    color: "emerald",
  },
];

export const CS501_RESOURCES: Record<string, Resource> = {
  R01: { label: "Fairlearn Documentation", url: "https://fairlearn.org/main/" },
  R02: { label: "AI Fairness 360 Documentation", url: "https://aif360.readthedocs.io/en/stable/" },
  R03: { label: "scikit-learn — Model Evaluation", url: "https://scikit-learn.org/stable/modules/model_evaluation.html" },
  R04: { label: "SHAP Documentation", url: "https://shap.readthedocs.io/" },
  R05: { label: "Captum Documentation", url: "https://captum.ai/" },
  R06: { label: "LIME Repository and Documentation", url: "https://github.com/marcotcr/lime" },
  R07: { label: "MITRE ATLAS", url: "https://atlas.mitre.org/" },
  R08: { label: "OWASP Machine Learning Security Top 10", url: "https://owasp.org/www-project-machine-learning-security-top-10/" },
  R09: { label: "NIST AI Risk Management Framework", url: "https://www.nist.gov/itl/ai-risk-management-framework" },
  R10: { label: "Microsoft Presidio Documentation", url: "https://microsoft.github.io/presidio/" },
  R11: { label: "Regulation (EU) 2024/1689 — Artificial Intelligence Act", url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj/eng" },
  R12: { label: "OECD AI Principles", url: "https://oecd.ai/en/ai-principles" },
  R13: { label: "Model Cards for Model Reporting", url: "https://research.google/pubs/model-cards-for-model-reporting/" },
};

export const CS501_ACTIVITIES: Activity[] = [
  {
    id: "CS501-ACT-01",
    part: "I",
    icon: "ethics",
    hours: 30,
    title: "Build a Fairness Auditor",
    desc: "A programmatic bias auditing pipeline evaluating demographic parity, equalized odds, and mitigation trade-offs.",
    outcome:
      "Check whether an AI model treats different groups fairly and test practical ways to reduce unfair outcomes.",
    subs: [
      {
        id: "CS501-SUB-1.1",
        title: "Learn the Basics of AI Fairness",
        hours: 3,
        tag: "Understand Core Ideas",
        evidence: "Short notes explaining protected groups, fairness and common sources of bias",
        standard: "Explains why overall accuracy alone cannot prove that a model is fair",
        resources: ["R01", "R02"],
      },
      {
        id: "CS501-SUB-1.2",
        title: "Check Group Results",
        hours: 2,
        tag: "Apply Principles",
        evidence: "Table comparing selection rates and model results across groups",
        standard: "Calculates group-level results correctly and avoids unsupported conclusions",
        resources: ["R01"],
      },
      {
        id: "CS501-SUB-1.3",
        title: "Compare Model Errors",
        hours: 4,
        tag: "Analyse the Problem",
        evidence: "False-positive and false-negative comparison across groups",
        standard: "Identifies where errors are concentrated and explains who may be affected",
        resources: ["R01", "R03"],
      },
      {
        id: "CS501-SUB-1.4",
        title: "Build the Fairness Auditor",
        hours: 9,
        tag: "Design and Build",
        evidence: "Working notebook or application, dataset description, fairness metrics and tests",
        standard: "Auditor produces repeatable group and error comparisons from documented data",
        resources: ["R01", "R02"],
      },
      {
        id: "CS501-SUB-1.5",
        title: "Test Bias-Reduction Methods",
        hours: 4,
        tag: "Apply Principles",
        evidence: "Before-and-after comparison for at least one mitigation method",
        standard: "Shows whether fairness improved and records any accuracy or operational trade-off",
        resources: ["R01", "R02"],
      },
      {
        id: "CS501-SUB-1.6",
        title: "Review and Defend the Findings",
        hours: 4,
        tag: "Review and Justify",
        evidence: "Review notes, presentation and response to questions",
        standard: "Student explains metric choice, limitations and possible impact on affected groups",
        resources: ["R01", "R09"],
      },
      {
        id: "CS501-SUB-1.7",
        title: "Improve and Finalise the Audit",
        hours: 4,
        tag: "Design and Build",
        evidence: "Corrected analysis, final report and limitations statement",
        standard: "Review findings are addressed and claims remain traceable to data and calculations",
        resources: ["R01", "R02"],
      },
    ],
  },
  {
    id: "CS501-ACT-02",
    part: "II",
    icon: "audit",
    hours: 30,
    title: "Build a Model Interpreter",
    desc: "An interpretability toolkit using SHAP, Captum, and LIME to generate local and global decision explanations.",
    outcome:
      "Explain which inputs influenced an AI decision and communicate the explanation clearly to technical and non-technical users.",
    subs: [
      {
        id: "CS501-SUB-2.1",
        title: "Learn Why AI Explanations Matter",
        hours: 3,
        tag: "Understand Core Ideas",
        evidence: "Notes comparing global and individual explanations",
        standard: "Explains what each type of explanation can and cannot show",
        resources: ["R04", "R05"],
      },
      {
        id: "CS501-SUB-2.2",
        title: "Check Important Features",
        hours: 2,
        tag: "Apply Principles",
        evidence: "Feature-importance output for a selected model",
        standard: "Identifies influential features without presenting importance as proof of causation",
        resources: ["R04"],
      },
      {
        id: "CS501-SUB-2.3",
        title: "Explain One Prediction",
        hours: 4,
        tag: "Analyse the Problem",
        evidence: "Local explanation for one correct and one incorrect prediction",
        standard: "Connects the model output to relevant inputs and identifies misleading explanations",
        resources: ["R04", "R06"],
      },
      {
        id: "CS501-SUB-2.4",
        title: "Build the Model Interpreter",
        hours: 9,
        tag: "Design and Build",
        evidence: "Working explanation interface with text, table or visual output",
        standard: "Interface provides repeatable explanations and identifies the model, version and input used",
        resources: ["R04", "R05", "R06"],
      },
      {
        id: "CS501-SUB-2.5",
        title: "Test Visual and Text Explanations",
        hours: 4,
        tag: "Apply Principles",
        evidence: "Feature plot, image attention map or token-influence view appropriate to the model",
        standard: "Explanation is readable, technically appropriate and does not hide uncertainty",
        resources: ["R04", "R05"],
      },
      {
        id: "CS501-SUB-2.6",
        title: "Review and Defend the Explanation",
        hours: 4,
        tag: "Review and Justify",
        evidence: "User-review notes, presentation and technical defence",
        standard: "Student explains the method, limitations, stability and intended audience",
        resources: ["R04", "R09"],
      },
      {
        id: "CS501-SUB-2.7",
        title: "Improve the Explanation Experience",
        hours: 4,
        tag: "Design and Build",
        evidence: "Revised interface, plain-language summary and limitations note",
        standard: "Feedback is resolved and the final explanation is understandable without overstating certainty",
        resources: ["R04", "R05"],
      },
    ],
  },
  {
    id: "CS501-ACT-03",
    part: "III",
    icon: "security",
    hours: 30,
    title: "Conduct an AI Red Team Exercise",
    desc: "Adversarial vulnerability assessment referencing MITRE ATLAS, OWASP ML Security, and Presidio privacy filters.",
    outcome:
      "Test how an AI system responds to manipulated inputs, unsafe training data and personal information, then recommend practical safeguards.",
    subs: [
      {
        id: "CS501-SUB-3.1",
        title: "Learn Common AI Security Risks",
        hours: 3,
        tag: "Understand Core Ideas",
        evidence: "Threat notes covering adversarial inputs, poisoning, privacy and misuse",
        standard: "Correctly explains the selected threats and keeps testing within an approved safe environment",
        resources: ["R07", "R08"],
      },
      {
        id: "CS501-SUB-3.2",
        title: "Prepare a Safe Test Plan",
        hours: 2,
        tag: "Review and Justify",
        evidence: "Approved scope, rules, test cases and rollback plan",
        standard: "Defines clear boundaries, avoids real-world harm and protects sensitive information",
        resources: ["R07", "R09"],
      },
      {
        id: "CS501-SUB-3.3",
        title: "Test Manipulated Inputs",
        hours: 4,
        tag: "Analyse the Problem",
        evidence: "Controlled adversarial examples and model-response comparison",
        standard: "Demonstrates a reproducible weakness without targeting real users or external systems",
        resources: ["R07", "R08"],
      },
      {
        id: "CS501-SUB-3.4",
        title: "Run the Red Team Exercise",
        hours: 9,
        tag: "Design and Build",
        evidence: "Test harness, execution logs, attack scenarios and risk register",
        standard: "Exercise covers approved threats, records results and avoids destructive or unauthorized actions",
        resources: ["R07", "R08"],
      },
      {
        id: "CS501-SUB-3.5",
        title: "Check Data Poisoning and Privacy",
        hours: 4,
        tag: "Analyse the Problem",
        evidence: "Poisoning scenario, personal-data test and filtering evidence",
        standard: "Identifies unsafe data and demonstrates appropriate validation or redaction controls",
        resources: ["R08", "R10"],
      },
      {
        id: "CS501-SUB-3.6",
        title: "Present Risks and Defend Safeguards",
        hours: 4,
        tag: "Review and Justify",
        evidence: "Findings report, live demonstration and response to questions",
        standard: "Risks are prioritized by evidence and recommended controls are practical and proportionate",
        resources: ["R07", "R09"],
      },
      {
        id: "CS501-SUB-3.7",
        title: "Fix and Retest the System",
        hours: 4,
        tag: "Design and Build",
        evidence: "Corrected implementation and before-and-after security results",
        standard: "High-priority findings are addressed and regression tests confirm the improvement",
        resources: ["R07", "R08"],
      },
    ],
  },
  {
    id: "CS501-ACT-04",
    part: "IV",
    icon: "ethics",
    hours: 30,
    title: "Build an AI Compliance Dashboard",
    desc: "An operational governance dashboard implementing EU AI Act risk tiers, Model Cards, and human-in-the-loop overrides.",
    outcome:
      "Record an AI system's purpose, risk, controls, limitations and human oversight using recognized governance guidance.",
    subs: [
      {
        id: "CS501-SUB-4.1",
        title: "Learn Responsible AI Governance",
        hours: 3,
        tag: "Understand Core Ideas",
        evidence: "Notes comparing the EU AI Act, NIST AI RMF and OECD AI Principles",
        standard:
          "Explains the purpose of governance, risk management, transparency and human oversight in simple terms",
        resources: ["R11", "R09", "R12"],
      },
      {
        id: "CS501-SUB-4.2",
        title: "Classify the AI System's Risk",
        hours: 2,
        tag: "Analyse the Problem",
        evidence: "Educational risk-classification worksheet with stated assumptions",
        standard:
          "Uses the selected framework consistently and clearly marks uncertainty and required expert review",
        resources: ["R11", "R09"],
      },
      {
        id: "CS501-SUB-4.3",
        title: "Create the Model Card",
        hours: 4,
        tag: "Apply Principles",
        evidence: "Model card covering purpose, data, performance, limits and intended users",
        standard: "Document is complete, understandable and does not hide known limitations or unsuitable uses",
        resources: ["R13"],
      },
      {
        id: "CS501-SUB-4.4",
        title: "Build the Compliance Dashboard",
        hours: 9,
        tag: "Design and Build",
        evidence: "Working dashboard, control register, evidence links and version history",
        standard: "Dashboard shows system owner, risk, controls, evidence, open issues and review status clearly",
        resources: ["R11", "R09"],
      },
      {
        id: "CS501-SUB-4.5",
        title: "Add Human Review and Stop Controls",
        hours: 4,
        tag: "Design and Build",
        evidence: "Human-review flow, override control and audit-log evidence",
        standard: "Authorized humans can review, pause or override the AI and all actions are traceable",
        resources: ["R11", "R09"],
      },
      {
        id: "CS501-SUB-4.6",
        title: "Conduct the Governance Review",
        hours: 4,
        tag: "Review and Justify",
        evidence: "Review minutes, gap list and decision record",
        standard: "Student identifies missing evidence, unresolved risk and ownership before approval",
        resources: ["R11", "R09", "R12"],
      },
      {
        id: "CS501-SUB-4.7",
        title: "Improve and Publish the Governance Record",
        hours: 4,
        tag: "Design and Build",
        evidence: "Updated dashboard, closed findings and approved governance summary",
        standard:
          "Findings are resolved or formally accepted, and the published record is clear and versioned",
        resources: ["R11", "R09"],
      },
    ],
  },
];

export const CS501_DATA: CourseData = {
  slug: "cs501",
  course: CS501_COURSE,
  shortDesc:
    "An elective master's curriculum in responsible AI engineering covering bias quantification (Fairlearn, AIF360), explainable models (SHAP, Captum, LIME), adversarial red teaming (MITRE ATLAS, OWASP ML Top 10), and regulatory governance (EU AI Act, NIST AI RMF, Model Cards).",
  status: "active",
  parts: CS501_PARTS,
  activities: CS501_ACTIVITIES,
  resources: CS501_RESOURCES,
};
